# Generated by Django 5.2.13 on 2026-05-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('drivers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cars.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='drivers.driver')),
                ('orders', models.ManyToManyField(blank=True, related_name='routes', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
