# Generated by Django 5.2.13 on 2026-05-07 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('license_number', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='License number must be 4-32 chars: A-Z, 0-9, dash.', regex='^[A-Z0-9\\-]{4,32}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
    ]
