# Generated by Django 5.2.13 on 2026-05-07 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('license_plate', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='License plate must be 4-16 chars: A-Z, 0-9, dash or space.', regex='^[A-Z0-9\\- ]{4,16}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('brand', 'model'),
            },
        ),
    ]
