# Generated by Django 5.2.13 on 2026-05-07 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Phone must be 6-32 chars, digits and +-() space.', regex='^\\+?[0-9 \\-()]{6,32}$')])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
    ]
